### ISSUE TITLE
First boot issue without previous yaml

### ISSUE THREAD

**Issue by ZeroInputCtrl** [jkeljo/hacs-greeneye-monitor#22]
## Version of the custom_component

2023-05-30

## Configuration

```yaml
```

## Describe the bug

First time loading the component i got the following error
`2023-06-04T13:20:12.587529761Z 2023-06-04 14:20:12.585 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration greeneye_monitor: cannot import name 'MonitorType' from 'greeneye.monitor' (/usr/lib/python3.10/site-packages/greeneye/monitor.py)`
When trying to reboot from within HA i got
`2023-06-04T13:21:52.587369312Z 2023-06-04 14:21:52.585 ERROR (MainThread) [homeassistant.components.homeassistant] The system cannot restart because the configuration is not valid: Component error: greeneye_monitor - cannot import name 'MonitorType' from 'greeneye.monitor' (/usr/lib/python3.10/site-packages/greeneye/monitor.py)`

A note, i already had my yaml commented out (my bad) but this seems like maybe if someone is starting from scratch the component may not load? After a reboot with the yaml for old GEM uncommented everything went smoothly.

## Debug log

```text
2023-06-04T13:21:52.599984775Z 2023-06-04 14:21:52.593 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547585842320] The system cannot restart because the configuration is not valid: Component error: greeneye_monitor - cannot import name 'MonitorType' from 'greeneye.monitor' (/usr/lib/python3.10/site-packages/greeneye/monitor.py)

2023-06-04T13:21:52.600096719Z Traceback (most recent call last):

2023-06-04T13:21:52.600120979Z   File "/usr/lib/python3.10/site-packages/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service

2023-06-04T13:21:52.600140571Z     await hass.services.async_call(

2023-06-04T13:21:52.600158442Z   File "/usr/lib/python3.10/site-packages/homeassistant/core.py", line 1849, in async_call

2023-06-04T13:21:52.600176942Z     task.result()

2023-06-04T13:21:52.600194182Z   File "/usr/lib/python3.10/site-packages/homeassistant/core.py", line 1889, in _execute_service

2023-06-04T13:21:52.600249812Z     await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(

2023-06-04T13:21:52.600271682Z   File "/usr/lib/python3.10/site-packages/homeassistant/helpers/service.py", line 874, in admin_handler

2023-06-04T13:21:52.600289108Z     await result

2023-06-04T13:21:52.600306608Z   File "/usr/lib/python3.10/site-packages/homeassistant/components/homeassistant/__init__.py", line 181, in async_handle_core_service

2023-06-04T13:21:52.600324349Z     raise HomeAssistantError(

2023-06-04T13:21:52.600341479Z homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Component error: greeneye_monitor - cannot import name 'MonitorType' from 'greeneye.monitor' (/usr/lib/python3.10/site-packages/greeneye/monitor.py)



```

**Comment by jkeljo** [comment]
Hm, that suggests that somehow when you installed the HACS component, it didn't pull down the latest version of its dependency `greeneye_monitor` package. (`MonitorType` was introduced in 4.0, and Home Assistant core uses 3.0.3.)

I haven't been able to reproduce this issue locally, even with a fresh Home Assistant/HACS install. I wonder if it was just a fluke where the first time you restarted HA failed to upgrade the dependency, but then succeeded the next time... You installed via HACS, right, not by manually copying files into custom_components or something?

**Comment by ZeroInputCtrl** [comment]
Correct installed via HACS, on install the first error appeared. I'm not too concerned about this as everything seems to work now. Mainly just reported in case it is reproducible.

**Comment by rogerfar** [comment]
Just fyi, I updated HACS first because it was quite a few versions behind, then it worked flawlessly.

**Comment by jkeljo** [comment]
I don't think there's anything left to do here.
